server:
  port: 8080
  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: on_param  # Response 에 Stack Trace 를 표시할지 (never | always | on_param) on_trace_params 은 deprecated
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JavaStudy?autoReconnect=true
    username: allen
    password: allen123!
  session:
    store-type: jdbc
    jdbc:
      table-name: SESSIONS
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database: mysql
    show-sql: true
security:
  jwt:
    token:
      secret-key: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK